pipelines:
  - name: pipelines_approval
    steps:
      - name: approval_step
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin
        execution:
          onExecute:
            - echo "Hello"
            - echo $step_approved_by
            - echo $step_approved_comment
            - echo $step_approved_at
