template: true 
valuesFilePath: ./values.yml

resources:
  - name: gitRepoTest
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}

pipelines:
  - name: pinned_version_test
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: gitRepoTest
        execution:
          onExecute:
            - res_<resource_name>_resourcePath
            -  ls
